from __future__ import annotations

import logging
import os
import re as _re
import subprocess
from typing import Any

from tools import Tool, ToolContext

from src.logging_config import get_logger

logger = get_logger(__name__)

DEFAULT_TIMEOUT = 30

# ── Pre-execution command scanner patterns ────────────────────────────────
# Each entry is (regex_pattern, description)

_ESCAPE_PATTERNS: list[tuple[str, str]] = [
    # Shell redirects (> and >>) to absolute paths (Unix / or Windows C:\) or paths with ../../
    (r'(?:(?:\d*>>?|&>>?)\s+)((?:[a-zA-Z]:)?[/\\]|\.\./)', "output redirect (> or >>) to a path outside the working directory"),
    # tee to absolute path
    (r'\btee\s+(-[aA]+\s+)?((?:[a-zA-Z]:)?[/\\]|\.\./)', "tee to a path outside the working directory"),
    # mv with target outside
    (r'\bmv\s+\S+\s+((?:[a-zA-Z]:)?[/\\]|\.\./)', "mv target resolves outside the working directory"),
    # cp with target outside
    (r'\bcp\s+\S+\s+((?:[a-zA-Z]:)?[/\\]|\.\./)', "cp target resolves outside the working directory"),
    # rm on absolute paths or outside
    (r'\brm\s+[-rf]*\s+((?:[a-zA-Z]:)?[/\\]|\.\./)', "rm target resolves outside the working directory"),
    # ln with target outside
    (r'\bln\s+-[sf]+\s+\S+\s+((?:[a-zA-Z]:)?[/\\]|\.\./)', "ln target resolves outside the working directory"),
    # chmod/chown on files outside
    (r'\b(?:chmod|chown)\s+\S+\s+((?:[a-zA-Z]:)?[/\\]|\.\./)', "chmod/chown target resolves outside the working directory"),
    # dd with of= outside
    (r'\bdd\b.*\bof=((?:[a-zA-Z]:)?[/\\]|\.\./)', "dd output file resolves outside the working directory"),
]


def _check_command_for_outside_writes(command: str, working_directory: str) -> str | None:
    """Check if a bash command attempts to write/move/delete files outside the working directory.

    Uses regex pattern matching to detect common file operations that target
    paths outside the working directory. Not a full sandbox (deliberately
    crafted commands may bypass this), but catches the vast majority of
    cases generated by LLMs.

    Returns an error message if a violation is detected, None otherwise.
    """
    from pathlib import Path

    for pattern, description in _ESCAPE_PATTERNS:
        match = _re.search(pattern, command)
        if match:
            # Do a quick sanity check — if the target resolves inside, allow it
            try:
                target = match.group(0).strip()
                path_match = _re.search(r'((?:[a-zA-Z]:)?[/\\][\w/.\-\\ :]+)', target)
                if path_match:
                    candidate = path_match.group(1)
                    resolved = Path(candidate).resolve()
                    resolved_wd = Path(working_directory).resolve()
                    resolved.relative_to(resolved_wd)
                    # It resolved inside the working directory — allow it
                    continue
            except (ValueError, IndexError):
                pass

            return (
                f"Error: Command blocked — {description}.\n"
                f"Working directory: '{working_directory}'\n"
                f"All file operations must stay within the working directory.\n"
                f"Matched pattern: {match.group(0)!r}"
            )
    return None


def execute(args: dict[str, Any], ctx: ToolContext) -> str:
    command = args.get("command")
    timeout = int(args.get("timeout", DEFAULT_TIMEOUT))
    workdir = args.get("workdir") or ctx.working_directory  # Default to working dir
    logger.info("execute: command=%s, timeout=%s, workdir=%s", command, timeout, workdir)
    if not command:
        return 'Error: missing required argument "command".'

    # Validate workdir is within the working directory
    error = ctx.validate_write_path(workdir)
    if error:
        return error

    # Pre-execution command scanner: block writes outside working dir
    scanner_error = _check_command_for_outside_writes(command, ctx.working_directory)
    if scanner_error:
        return scanner_error

    try:
        result = subprocess.run(
            command,
            shell=True,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=timeout,
            cwd=workdir,
        )
    except subprocess.TimeoutExpired:
        logger.warning("Command timed out after %ds: %s", timeout, command)
        return f"[Error] Command timed out after {timeout}s"
    except Exception as exc:
        logger.error("Command failed: %s", exc)
        return f"[Error] {exc}"

    # Post-execution: quick git diff check to detect writes outside working dir
    if result.returncode == 0:
        try:
            _diff_check = subprocess.run(
                ["git", "diff", "--stat"],
                capture_output=True, text=True, cwd=workdir,
                timeout=5,
            )
            if _diff_check.returncode == 0 and _diff_check.stdout:
                _changed_files = _diff_check.stdout.strip().split("\n")
                for _line in _changed_files:
                    _file_path = _line.split("|")[0].strip()
                    if _file_path:
                        _abs_path = os.path.join(workdir, _file_path)
                        err = ctx.validate_write_path(_abs_path)
                        if err:
                            # Revert the changes with git checkout
                            subprocess.run(
                                ["git", "checkout", "--", _file_path],
                                capture_output=True, cwd=workdir,
                                timeout=5,
                            )
                            return (
                                f"Command completed but wrote to file outside working directory. "
                                f"Changes reverted.\n{err}"
                            )
        except Exception:
            pass

    parts: list[str] = []
    if result.stdout:
        parts.append(result.stdout.rstrip("\n"))
    if result.stderr:
        parts.append(f"[stderr]\n{result.stderr.rstrip(chr(10))}")
    if result.returncode != 0:
        parts.append(f"\n[Exit code: {result.returncode}]")

    logger.info("Command completed (exit_code=%d, stdout_len=%d, stderr_len=%d)", result.returncode, len(result.stdout or ""), len(result.stderr or ""))
    return "\n".join(parts) if parts else "Command completed with no output."


bash_tool = Tool(
    name="bash",
    description=(
        "Run a shell command and return its output. Use this to compile, "
        "run tests, lint, install packages, or any other shell operation.\n\n"
        "WARNING: All file operations (write, move, delete, copy) must stay "
        "within the project's working directory. The tool enforces this by "
        "blocking commands that target paths outside the working directory."
    ),
    input_schema={
        "type": "object",
        "properties": {
            "command": {"type": "string", "description": "The shell command to execute"},
            "timeout": {"type": "number", "description": "Timeout in seconds (default: 30)"},
            "workdir": {
                "type": "string",
                "description": "Working directory for the command (default: project root)",
            },
        },
        "required": ["command"],
    },
    execute=execute,
    read_only=False,
)
